CREATE DATABASE HabbitTracker;

USE HabbitTracker;

CREATE TABLE Users
(
    UserID INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Email NVARCHAR(255) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(255) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE()
);

CREATE TABLE Categories
(
    CategoryID INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE Habits
(
    HabitID INT IDENTITY(1,1) PRIMARY KEY,
    UserID INT NOT NULL,
    Name NVARCHAR(100) NOT NULL,
    Description NVARCHAR(500),
    CategoryID INT,
    TargetValue DECIMAL(10,2),
    Unit NVARCHAR(50),
    Frequency NVARCHAR(50) NOT NULL,
    Difficulty NVARCHAR(20),
    StartDate DATE NOT NULL,
    Status NVARCHAR(20) NOT NULL DEFAULT 'Active',
    CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),

    FOREIGN KEY (UserID) REFERENCES Users(UserID),
    FOREIGN KEY (CategoryID) REFERENCES Categories(CategoryID)
);

CREATE TABLE HabitLogs
(
    LogID INT IDENTITY(1,1) PRIMARY KEY,
    HabitID INT NOT NULL,
    Date DATE NOT NULL,
    Status NVARCHAR(30) NOT NULL,
    ActualValue DECIMAL(10,2),
    Notes NVARCHAR(500),
    CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),

    FOREIGN KEY (HabitID) REFERENCES Habits(HabitID),

    CONSTRAINT UQ_HabitLogs_HabitID_Date UNIQUE (HabitID, Date)
);

CREATE TABLE Reflections
(
    ReflectionID INT IDENTITY(1,1) PRIMARY KEY,
    UserID INT NOT NULL,
    Date DATE NOT NULL,
    Mood NVARCHAR(30),
    Notes NVARCHAR(500),
    CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),

    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);
